version: '3'
services: 
  server: 
    build: 
      context: ./server
    container_name: server
    ports: 
      - "5000:5000"
  client: 
    container_name: app
    depends_on:
      - server
    ports: 
      - "3000:3000"
    build: 
      context: ./client
  # nginx: 
  #   container_name: nginx
  #   depends_on: 
  #     - server
  #     - client
  #   ports: 
  #     - "80:80"
  #   build:
  #     context: ./nginx